# Generated by Django 5.2.12 on 2026-04-11 09:28

from django.db import migrations, models


def update_existing_users(apps, schema_editor):
    """
    Обновляет существующих пользователей:
    - Активные пользователи помечаются как подтвержденные
    - Суперпользователи помечаются как подтвержденные и активные
    """
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        if user.is_superuser or user.is_staff:
            user.is_email_confirmed = True
            user.is_active = True
            user.save()
        elif user.is_active:
            user.is_email_confirmed = True
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(update_existing_users, migrations.RunPython.noop),
    ]
