# Generated by Django 5.2.12 on 2026-04-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_email_token_user_is_email_confirmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="confirmation_email_last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
