# Generated by Django 5.2.12 on 2026-04-29 18:00

from django.db import migrations
from django.utils import timezone


def backfill_email_token_created_at(apps, schema_editor):
    User = apps.get_model("users", "User")
    (
        User.objects.filter(email_token_created_at__isnull=True, email_token__isnull=False)
        .exclude(email_token="")
        .update(email_token_created_at=timezone.now())
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_email_token_created_at"),
    ]

    operations = [
        migrations.RunPython(backfill_email_token_created_at, migrations.RunPython.noop),
    ]
