# Generated by Django 5.2.12 on 2026-04-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_productvariant_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="size",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
