# Generated by Django 5.2.14 on 2026-05-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_product_commercial_fields_variant_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="thumbnails/"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="thumbnail_source_name",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="productimage",
            name="thumbnail_source_size",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="original/"),
        ),
    ]
