# Generated by Django 5.2.12 on 2026-04-26 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_user_protect"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OrderStatusTransition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "transition_type",
                    models.CharField(
                        choices=[
                            ("dashboard_status", "Статус dashboard"),
                            ("order_status", "Статус заказа"),
                            ("fulfillment_status", "Статус исполнения"),
                            ("payment_status", "Статус оплаты"),
                        ],
                        max_length=32,
                    ),
                ),
                ("from_value", models.CharField(max_length=64)),
                ("to_value", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_status_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_transitions",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Переход статуса заказа",
                "verbose_name_plural": "Переходы статусов заказа",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
