# Generated by Django 5.2.13 on 2026-06-01 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_checkout_session_ip"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderNotificationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("created", "Заказ принят"),
                            ("cancelled", "Заказ отменен"),
                            ("ready", "Готов к выдаче"),
                            ("paid", "Оплата подтверждена"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Ожидает отправки"), ("sent", "Отправлено"), ("failed", "Ошибка")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("task_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="orders.order",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_order_notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал уведомления заказа",
                "verbose_name_plural": "Журнал уведомлений заказов",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["order", "-created_at"], name="order_notif_order_created_idx"),
                    models.Index(fields=["order", "status"], name="order_notif_order_status_idx"),
                ],
            },
        ),
    ]
